<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tracklist [
<!ELEMENT tracklist	    (track*, interpret*)>

<!ELEMENT track         (name, length, review*)>
<!ATTLIST track         id  ID	#REQUIRED
                        style   (rock|funk|hiphop|klassik) "rock">
<!ELEMENT name          (#PCDATA)>
<!ELEMENT length	    (#PCDATA)>
<!ELEMENT review	    (#PCDATA | link)*>

<!ELEMENT link		    (#PCDATA)>
<!ATTLIST link          ref     IDREF   #IMPLIED>

<!ELEMENT interpret     (band | soloartist)>
<!ATTLIST interpret	    id	ID	#REQUIRED>
<!ELEMENT band		    (name, person+)>
<!ELEMENT soloartist    (person)>

<!ELEMENT person	    (firstname?, name, instrument*)>
<!ELEMENT firstname	    (#PCDATA)>
<!ELEMENT instrument    (#PCDATA)>
<!ATTLIST person        gender	(male|female) "female">
]>

<tracklist>
    <track id="arnalds-eyesshut" style="klassik">
        <name>Eyes Shut - Nocturne G Minor</name>
        <length>4.22</length>
        <review>
            A dreamlike story arc you wish would never end.
        </review>
        <review>
            <link ref="arnalds-eyesshut">https://review.com/eyesshut</link>
        </review>
    </track>
    
    <interpret id="arnalds">
        <soloartist>
            <person gender="male">
                <firstname>Olafur</firstname>
                <name>Arnalds</name>
                <instrument>Piano</instrument>
            </person>
        </soloartist>
    </interpret>
    
    <interpret id="omam">
        <band>
            <name>Of monsters and men</name>
            <person gender="female">
                <name>Nanna Brynd√≠s Hilmarsdottir</name>
                <instrument>Vocal</instrument>
            </person>
            <person gender="male">
                <name>Krisjef Rosenkranz Krisjefsson</name>
                <instrument>Guitar</instrument>
            </person>
            <!-- Some are missing... -->
        </band>
    </interpret>
</tracklist>
